### PR TITLE
`CosmeticUser.getCosmetics()` changes

### LINKED ISSUE #80: `CosmeticUser.getCosmetics()` return type
**Note:** *As of writing this issue, the method name is `CosmeticUser.getCosmetic()`. I have opened a PR to change this naming to `CosmeticUser.getCosmetics()` and will be referring to the method as the latter.*

Currently, `CosmeticUser.getCosmetics()` returns a mutable `Collection<Cosmetic>`. However, I feel that an `ImmutableCollection<Cosmetic>` return type would be better instead.

Returning an `ImmutableCollection<Cosmetic>` has several advantages over a mutable `Collection<Cosmetic>` one. 

```java
// Old
public Collection<Cosmetic> getCosmetics() {
    return playerCosmetics.values();
}

// New
public ImmutableCollection<Cosmetic> getCosmetics() {
    // Immutable casting 
}
```

Firstly, it ensures that the collection cannot be accidentally modified by other parts of the code, which can lead to unexpected behavior and bugs. With an immutable collection, the state of the collection remains constant, making it easier to reason about and debug.

Secondly, returning an `ImmutableCollection<Cosmetic>` also communicates the intent of the method more clearly. Since `CosmeticUser.getCosmetics()` is only used to retrieve the cosmetics of a user, there is no need for the collection to be mutable. An immutable collection makes it clear that the collection should not be modified and reinforces the intent of the method.

Just to clarify, what’s returned from `HashMap.values()` is a copy of a `Collection`. Modifying the returned `Collection<Cosmetic>` won’t change the `HashMap` in `CosmeticUser` at all, so making it an `ImmutableCollection<Cosmetic>` just makes more sense. If a developer wishes to change the contents of the `HashMap`, then specific methods that make controlled changes should be in place instead. 

*Also this isn't a real benefit for now, nor may it ever be but immutability promotes thread-safety. If the `CosmeticUser.getCosmetics()` method is accessed by multiple threads simultaneously, a mutable collection can result in race conditions and other concurrency issues. An immutable collection eliminates this risk, ensuring that the state of the collection remains consistent regardless of concurrent access.*

### PR DESCRIPTION
**Pull request by Craftinators**
This PR request changes the `CosmeticUser.getCosmetic()` method to `CosmeticUser.getCosmetics()` in order to improve the clarity and consistency of the codebase.

The change was made to reflect the fact that the method returns multiple cosmetic items rather than just one. The new method name is more accurate and easier to understand, making it more intuitive for developers to work with.

*All references to the old method name have been updated throughout the codebase, including in comments and documentation.*

### CODE REVIEW

File: common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java [hunk 1]
```diff
@@ -77,7 +77,7 @@ public Cosmetic getCosmetic(CosmeticSlot slot) {
         return playerCosmetics.get(slot);
     }
 
-    public Collection<Cosmetic> getCosmetic() {
```
Comment (LoJoSho) [inline common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java:80]: Keep this and deprecated it so that plugins currently using HMCC don't break right away.

**Review by LoJoSho — CHANGES_REQUESTED** [review]

File: common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java (hunk 1 above)
Comment (LoJoSho) [reply common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java:80]: Possibly also make the new method immutable as talked about in #80

File: common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java [hunk 2]
```diff
@@ -77,10 +78,19 @@ public Cosmetic getCosmetic(CosmeticSlot slot) {
         return playerCosmetics.get(slot);
     }
 
+    @Deprecated
     public Collection<Cosmetic> getCosmetic() {
         return playerCosmetics.values();
     }
 
+    public Collection<Cosmetic> getCosmetics() {
```
Comment (LoJoSho) [inline common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java]: I am a bit confused why we would be making such a change if we don't also make this Immutable. We just deprecated getCosmetic() for no reason then.

**Review by LoJoSho — CHANGES_REQUESTED** [review]

File: common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java (hunk 2 above)
Comment (Craftinators) [reply common/src/main/java/com/hibiscusmc/hmccosmetics/user/CosmeticUser.java]: You’re right I’ll apply the change in a bit

**Comment by Craftinators** [comment]
@LoJoSho Applied the requested changes

**Comment by Craftinators** [comment]
This should also resolve #80

**Review by LoJoSho — APPROVED** [review]
Looks good to me, thank you for another wonderful PR!
